### ISSUE TITLE
Remote kernel setup with original jupyter notebook?

### ISSUE THREAD

**Issue by MaximilianR** [googledatalab/datalab#1011]
The remote kernel functionality is really impressive - having the ability to access local notebooks, but with the code executing on the server.

How 'separable' is that from the datalab product vs the jupyter notebook? I've had a quick look through the code but can't quickly figure it out. Ideally we would run jupyter notebooks using the same remote kernel functionality.

Thanks
Max

**Comment by ojarjur** [comment]
This is entirely separable from Datalab.

The functionality is built in to [a Jupyter notebook server extension](https://github.com/jupyter/kernel_gateway_demos/tree/master/nb2kg), and all we do in Datalab is enable that extension.

The caveat is that this is all or nothing; you either run all kernels via a remote gateway or run all of them locally.

What we do in Datalab is enable that extension conditionally. If you specify the VM to which we should connect, then we enable the extension and point it at an SSH tunnel to that VM. Otherwise, we do not enable the extension.

If you want to do the same in Jupyter, then first start up the SSH tunnel with:

    gcloud compute ssh --quiet \
    --project "${PROJECT_ID}" \
    --zone "${ZONE}" \
    --ssh-flag="-fNL" \
    --ssh-flag="localhost:8082:localhost:8080" \
    "${INSTANCE}"

... where PROJECT_ID, ZONE, and INSTANCE are all replaced with the corresponding values for your VM.

Then, before you run Jupyter, set the "KG_URL" environment variable to "http://localhost:8082", and add the command flags specified [here](https://github.com/jupyter/kernel_gateway_demos/tree/master/nb2kg#run-notebook-server).

Of course, you can change the local port to something else, but make sure it matches the entry in the "gcloud compute ssh" command.

**Comment by MaximilianR** [comment]
Thanks a lot for the full response @ojarjur
