### ISSUE TITLE
Not able to connect to GCE VM datalab kernel

### ISSUE THREAD

**Issue by josecelaya** [googledatalab/datalab#1043]
I just updated to the latest update and datalab is no longer working...

```
Failed to set up the SSH tunnel to the VM vm-instance-datalab
If the VM was recently created, then it may still be starting up, and retrying the command may work.
```
I have removed containers and I have also restarted GCE VM. Even redeployed GCE VM. I have also tried `gcloud compute ssh` and I can connect to it from my computer.

**Comment by ojarjur** [comment]
Sorry you hit this, and thanks for reporting it to us.

It seems that with the latest release the datalab-gateway image immediately exits after starting.

I've rolled back that image to the previous release while we investigate.

I'll also look into how I can extend our existing release validation checks to catch this.

**Comment by VathsalaAchar** [comment]
@ojarjur I did the update just now and I get the same message. Is the image that has been partially rolled back sitting elsewhere?

**Comment by josecelaya** [comment]
@VathsalaAchar I tried the same yesterday evening and also tried reverting to previous container images dating back to October, none worked. Now, if the issue is on the gateway VM, perhaps is that container that got reverted. 

@ojarjur if my assessment is correct, is reseting VM enough? Perhaps I need to redeploy un which case I need to delete and create a new one.

**Comment by chmeyers** [comment]
Looking at the registry, the current latest tag is on the build from 10/13.

Specifically this one:
docker pull gcr.io/cloud-datalab/datalab-gateway@sha256:4c72e00fb46a9f127f7b93affc20534f75ff6965d28294b135fd0ebe3222eea4

@josecelaya Yes, it is the Gateway VM that has the bad Docker image.  I'm not sure if resetting it will work, though.

**Comment by josecelaya** [comment]
@chmeyers I tried reseting, deleting and redeploying and did not work. :( 👎 👎

**Comment by ojarjur** [comment]
@josecelaya It looks like there were (different) newly introduced issues in both the frontend image and the backend one.

I should have just done a full roll-back, but instead only rolled back the backend image. That was a mistake on my part and I am sorry that it affected you.

I have now fully rolled back both images and run through the quickstart to make sure that it is working again with the previous release.

Please let us know if that fixes things for you now (since you already deleted and recreated the VM, you should just have to `docker pull gcr.io/cloud-datalab/datalab:local` and then restart the Datalab frontend).

However, even if it works for you, don't close this bug yet. I'm going to use this to track the new additional safeguards that we need to add to the release process.

I am thinking that the first things we should add are:

1. Run the notebooks inside of both the gateway image and the frontend image rather than just the frontend image ([this part](https://github.com/googledatalab/datalab/blob/master/tools/release/publish.sh#L45) of the release script). I'm not aware of potential errors this can catch (since it is essentially testing the shared base image, but it doesn't hurt).
2. Run the gateway image locally and make sure that it responds to API requests (e.g. `curl http://localhost:8080/api/kernelspecs`).
3. Create a VM with the gateway image, run a frontend image pointing at it, and make sure that the frontend server starts up and serves requests. Ideally, this would also run notebooks via the UI, but we don't have any sort of web driver tests written yet, and improving the release process should not wait for creating a test framework that does not yet exist.
4. Automate the rollback process, and document our rollback policy (i.e. that we should always do a full rollback first).

**Comment by VathsalaAchar** [comment]
@ojarjur Thank you that fixed it!

**Comment by josecelaya** [comment]
Thank you. It works for me now.

**Comment by osslab** [comment]
Hi! I followed the instruction [Run Cloud Datalab on Google Cloud Platform](https://cloud.google.com/datalab/docs/quickstarts/quickstart-gcp).
When I launched docker locally, I can't find where should I get verification code. 
My docker terminal just show the message below. 

```
Please visit http://localhost:8081 to log in
Failed to log in to gcloud
```


When I access to http://localhost:8081. I requested me to allow access google account. After I allowed it, my docker container was just down and the message was "http://localhost:8081/oauthcallback?state=/exit&code=4/wKsLtVX0Lse3P06wI30-tr6qVUDgJi5B7L_Q2d8iAS4#"

**Comment by parthea** [comment]
@osslab Are you on Windows 10? If so, you may be hitting #1092

**Comment by osslab** [comment]
@parthea  I am on macOS and I am using docker on VirtualBox.

**Comment by parthea** [comment]
@osslab I am having the same issue on macOS 10.12.1 . The symptoms are identical to #1092 so I'm going to post a comment there.

**Comment by parthea** [comment]
@osslab Please remove the oauthcallback link in your earlier comment case it contains authentication information

**Comment by yebrahim** [comment]
Fixed by https://github.com/googledatalab/datalab/pull/1095.
