### ISSUE TITLE
Feature Request: Add ability to move notebooks within Datalab

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#1066]
[This StackOverflow post](http://stackoverflow.com/questions/34208517/datalab-moving-notebook-to-other-folder) has a few examples of how users could move notebooks to another directory in the current version of Datalab. In addition to the examples mentioned, users could also move notebooks using operating system commands (local file explorer, or `mv` command).

Having a **Move** button in the Datalab Toolbar to move notebooks for organisation purposes would create a better story.

**Comment by parthea** [comment]
After looking into this a bit more, I found this is already implemented as part of Jupyter Notebook 5.0. See jupyter/notebook#941

**Comment by e-lin** [comment]
Following this as I have the same request.

**Comment by nikhilk** [comment]
Was going to mention in #1337 which was about the entire file browsing ux and not just ability to move notebooks, but since thats been closed... I'll say it here.

1. We should get the terminal feature and make sure it works well from the perspective of how Datalab organizes the layout within the docker container (contents directory, data directory etc.)

2. Re-vamp (by dropping the Jupyter file browser experience) and build a better one that focuses on usability a lot more. My own impression is Jupyter provides a minimal experience, because most file management can be done by OS-specific and OS-native file management tools. However in our case, those don't apply. At that point it is also worth thinking about how to get the minimal Git flows incorporated (without duplicating an entire git client).

**Comment by larsbkrogvig** [comment]
I'm hereby expressing my +1 on this issue!

I ran into this and had to scratch my head for a while before I figured out how to move notebooks in the web interface. While I have no problem working around it, it feels like it could be a barrier for some users.

**Comment by yebrahim** [comment]
Yes the current UI doesn't not handle this sort of thing well. We're working on a UI rewrite that will provide these features and more.

**Comment by 414theodore** [comment]
@larsbkrogvig - Is there a way to do so in the web interface??

**Comment by larsbkrogvig** [comment]
Sorry, I have moved on from Datalab and I don't remember. A hacky workaround could be to execute a `mv` in a cell in a different notebook?
```sh
!mv the_other_notebook.ipynb destination/
```

**Comment by parthea** [comment]
Closing as obsolete.
