### ISSUE TITLE
Content-Type not set

### ISSUE THREAD

**Issue by bluecmd** [googledatalab/datalab#1067]
Hi,

I'm having some troubles rendering the pages from datalab. I'm using the instructions from https://cloud.google.com/datalab/docs/quickstarts/quickstart-gce-frontend and when I'm inside the VM this is what I get:

```
datalab-0:~$ curl -v http://localhost:8080
* About to connect() to localhost port 8080 (#0)
*   Trying 127.0.0.1...
* connected
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.26.0
> Host: localhost:8080
> Accept: */*
> 
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Date: Sat, 03 Dec 2016 21:17:17 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
<html>
  <head>
    <link rel="stylesheet" href="/static/style/style.min.css" type="text/css" />
    <title>
{..snip..]
```

Notice that there is no Content-Type, which causes my Chrome to render the page as plain text, not HTML.

When asking for static stuff it appears the Content-Type is set:
```
datalab-0:~$ curl -v http://localhost:8080/static/style/style.min.css | head
* About to connect() to localhost port 8080 (#0)
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* connected
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /static/style/style.min.css HTTP/1.1
> User-Agent: curl/7.26.0
> Host: localhost:8080
> Accept: */*
> 
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Content-Type: text/css
< Date: Sat, 03 Dec 2016 21:18:37 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
```

I'll work around this by forcing Content-Type if not set, but a fix would be much appreciated.

Thanks!

**Comment by jimmc** [comment]
I spent some time today trying to reproduce this bug and have been unable to do so. One thing I noticed is that, when using curl to get the root location (location:8080 from inside the container), it now gives me a 302 and a forwarding location, rather than directly giving me the content of the starting page. That looks to me like something changed in the way the root page is delivered, so perhaps there was also a change to how content-type is handled.

I'm going to close this issue as cant-reproduce. If you are still seeing this problem, please reopen, at which point I'd like to get some more details to help me reproduce it.
