### ISSUE TITLE
Cannot authenticate gcloud SDK on Windows when running kernels on GCE

### ISSUE THREAD

**Issue by yebrahim** [googledatalab/datalab#1092]
When the gateway image is set up to run on GCE, and a local Datalab container tries to load with `-e "GATEWAY_VM=vm_address"`, navigating to the localhost:8081 and clicking Allow on the authentication window returns ERR_EMPTY_RESPONSE and console outputs Failed to log in to gcloud.

OS: Windows 10 Pro.

**Comment by parthea** [comment]
This same issue also appears on macOS Sierra 10.12.1 / Docker 1.12.5 (14777)

The symptoms are the same:
I see `net::ERR_EMPTY_RESPONSE` in the browser console after clicking allow in the authentication window. I also see the following in Terminal:

```
Please visit http://localhost:8081 to log in
Failed to log in to gcloud
```

**Comment by ojarjur** [comment]
@parthea Thanks for correcting us about this not being a Windows-only issue.

I've also confirmed that it is broken on Linux, and that prior releases did not have this issue.

I'm going to run a binary search over our daily builds to figure out when it broke, and then try to track down the root cause.

In the mean time, for anyone hit by this, you can work around the issue in the following way:

1. Run the Datalab frontend completely locally (i.e. [this quickstart](https://cloud.google.com/datalab/docs/quickstarts/quickstart-local) ).
2. Sign in via the Datalab UI (the button in the top-right corner)
3. Kill that running Docker container and then restart with the command to connect to the local gateway.

**Comment by ojarjur** [comment]
The regression was introduced in the daily build from November 12, and seems to be caused by #1046 

More specifically, that change added an 'appSettings' variable to the 'auth' module that needs to be initialized before the auth handler will work. Our login server uses the auth module but does not initialize that variable, so the auth flow fails.

I have a change to make the login server initialize the auth module's appSettings variable, and will send out a PR for it shortly.

*However*, note that we do not have any additional releases planned until after the new year, so until another release goes out anyone hitting this issue will have to login via the locally-run Datalab before trying to connect to a kernel gateway.

**Comment by ojarjur** [comment]
I've rebuilt today's daily image with the submitted PR and confirmed that the login issue is resolved.

We will not publish another release before the new year, but if you want to use the daily build, the following commands should work:

    $ docker pull gcr.io/cloud-datalab/datalab:local-20161222
    $ docker run -it -p "127.0.0.1:8081:8080" -v "${HOME}:/content" \
        -e "GATEWAY_VM=${PROJECT}/${ZONE}/${INSTANCE}" \
        gcr.io/cloud-datalab/datalab:local-20161222

... of course, you have to replace the ${PROJECT} ${ZONE} and ${INSTANCE} bits with the appropriate value for your VM.
