### ISSUE TITLE
Cannot SSH to gateway VM from Windows

### ISSUE THREAD

**Issue by yebrahim** [googledatalab/datalab#1093]
Following the [GCE kernels quickstart](https://cloud.google.com/datalab/docs/quickstarts/quickstart-gcp) on Windows, SSH'ing to the gateway VM is failing with permissions on the SSH key being too open.

Updated property [core/project]. 
Updated property [compute/zone]. 
Will connect to the kernel gateway running on the GCE VM mc-datalab-vm as mcoomer 
Warning: Permanently added 'compute.2965227899996327447' (ECDSA) to the list of known hosts. 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 
@ WARNING: UNPROTECTED PRIVATE KEY FILE! @ 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 
Permissions 0755 for '/content/datalab/.config/.ssh/google_compute_engine' are too open. 
It is recommended that your private key files are NOT accessible by others. 
This private key will be ignored. 
key_load_private_type: bad permissions 
Permission denied (publickey). 
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255]. See https://cloud.google.com/compute/docs/troubleshooting#ssherrors for troubleshooting hints.

**Comment by xvanausloos** [comment]
Hi, I have the same issue.

**Comment by nikhilk** [comment]
I think the interesting question is whether this repros with the new datalab CLI? @ojarjur has it been tried on Windows?

This bug should probably be closed out... given the move to the new CLI.

**Comment by iairrozen** [comment]
I've just tried it with the new CLI and the issue remains.

**Comment by ojarjur** [comment]
@iairrozen Can you please file a separate bug for the issues you are seeing with the CLI? This bug is specifically about the kernel gateway path, which the CLI does not support.

In particular, in that new bug, can you provide the following?:

1. The version of gcloud you are running (i.e. the output of `gcloud version`)
2. The command you ran (please scrub out any details about the specific project and VM name)
3. The error message you saw (please scrub out any private information in the message)

@nikhilk I've tested the new CLI on windows and it worked for me, but I will investigate the issue that Lair is seeing once I get the relevant info.

**Comment by xvanausloos** [comment]
No solution? I succeed sometimes and sometimes not to connect to notebook.......weird..

**Comment by chmeyers** [comment]
Omar, please close if this bug is obsolete with the GA release.
