### ISSUE TITLE
Reconnect to Gateway Failure - w/ Steps & Possible Solution(s)

### ISSUE THREAD

**Issue by dovy** [googledatalab/datalab#1114]
Using gcr.io/cloud-datalab/datalab:local-20161222.

When I connect to the gateway of a newly created cluster all is great. If for any reason I close/terminate the connection and try to reconnect at a later date, it succeeds, but I cannot get the cluster to respond to me. I end up having to tear-down and recreate the cluster.

What do you suggest? I'd like to be able to reconnect to a beefy cluster that I leave running...

**Comment by dovy** [comment]
Here is the output from the debug log:

```
{"name":"app","hostname":"3dd96d763a3e","pid":191,"type":"jupyter","level":30,"msg":"[9000]: Initializing websocket connection /api/kernels/25a25e76-6835-4e81-a633-85fe5931fc85/channels\n","time":"2017-01-10T17:35:23.980Z","v":0}
{"name":"app","hostname":"3dd96d763a3e","pid":191,"type":"jupyter","level":30,"msg":"[9000]: Message signing is disabled.  This is insecure and not recommended!\n","time":"2017-01-10T17:35:23.981Z","v":0}
{"name":"app","hostname":"3dd96d763a3e","pid":191,"type":"jupyter","level":30,"msg":"[9000]: Connecting to ws://localhost:8082/api/kernels/25a25e76-6835-4e81-a633-85fe5931fc85/channels\n","time":"2017-01-10T17:35:23.983Z","v":0}
```

**Comment by dovy** [comment]
Debugged further using newest build: gcr.io/cloud-datalab/datalab:local-20170110

Couldn't use the newest gateway image since that repo is not exposed. I would love it if it were open. 

So the issue has to do with session management. Let me explain how to produce the bug, and how to get around it.

## Produce the bug
* Log into local instance with remote gateway
* Open a single notebook
* Run a command within the notebook and wait for execution to succeed.
* Close connection (ctrl + C), do not save or anything.
* Relaunch connection.
* Open Notebook
* No commands will execute again, and all notebooks will be disabled.

## Fix the Bug
* Log into local instance with remote gateway
* Open a single notebook
* Run a command within the notebook and wait for execution to succeed.
* Click on Running Sessions button and SHUT DOWN notebook
* Close connection (ctrl + C), do not save or anything.
* Relaunch connection.
* Open Notebook
* Everything works

So it seems like we're binding sessions to the user ID and not properly closing the session should the same user re-connect. However, the websocket connection thinks the user is connected and is probably sending the commands to the old websocket client, and disregarding the new client.

### Possible solutions
* Bind sessions to SESSION ID, not the user.
* Bind sessions to user as current, but with cleanup on user reconnect.

Either way, there needs to be a fix here. I'd call it pretty critical. Makes using notebooks a pain when I have to relaunch a cluster to just connect again.

**Comment by ojarjur** [comment]
Hi @dovy . Thanks for reaching out and reporting this.

I initially tried to reproduce what you report by following the instructions in [this quickstart](https://cloud.google.com/datalab/docs/quickstarts/quickstart-gcp)

When I tried to follow your reproduction steps, what I did was:

1. Create the gateway VM as described in that quickstart
2. Start the Datalab docker container on my local machine
3. Browse to localhost:8081, navigate to and open a notebook, and then run some code cells in that notebook.
4. Use <CTRL>+C to kill the running Datalab docker container on my local machine
5. Restart the Datalab docker container on my local machine
6. Browse to localhost:8081, open several different notebooks, and run code cells in them.

That sequence of operations seemed to work as expected (I didn't have any issues running code cells).

However, since you mentioned 'clusters' I thought maybe you were running a Datalab kernel gateway inside of a Dataproc cluster (along the lines of the instructions [here](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/tree/master/datalab) ).

I tried the same repro steps using a kernel gateway running in a Dataproc cluster, and then was able to reproduce the error.

I reached out to @pmkc who wrote that initilization action to ask about this, and he has a theory that this is due to the previously run Jupyter kernel still running. In the Dataproc setup, this causes problems because each kernel gets its own Spark context, and that means it uses enough resources that your cluster can't run multiple of them simultaneously.

The reason the old kernels are still running (and you cannot see them in the UI), is because of the way the Notebook server is structured (with the nb2kg extension). The Jupyter notebook server has separate concepts for "sessions" and "kernels". The list of sessions (and the mapping from sessions to kernels) is stored in the notebook server, and the list of kernels is stored in the kernel gateway.

Since killing the Datalab frontend also kills the notebook server, we no longer have a mapping from sessions to kernels. That means the frontend no longer knows anything about what the running kernels in the gateway represent, and so does not provide any UI for killing them.

Since kernel gateways are meant to be more than just a backend for a single notebook server, it makes sense that the notebook server wouldn't support killing kernels that it doesn't know about. Normally, this isn't an issue, but if your kernel gateway can only run one kernel at a time it becomes an issue.

You could manually kill the running kernels using curl:

    curl -X "GET" http://localhost:8081/api/kernels
    curl -X "DELETE" http://localhost:8081/api/kernels/${KERNEL_ID}

... but for the time being, the best workaround is to cleanly shut down your sessions before killing the Datalab frontend.

Alternatively, use that initialization action to run the Datalab frontend inside of the Dataproc cluster rather than merely the kernel gateway.

**Comment by pmkc** [comment]
Dangling interactive Spark sessions clogging up YARN resources is a problem the Dataproc team is working on handling better.

 If you need to kill a YARN application that is hanging somewhere, you can ssh into any VM on the cluster and run `yarn application kill APPLICATION_ID` as described [here](https://hadoop.apache.org/docs/stable/hadoop-yarn/hadoop-yarn-site/YarnCommands.html#application). You can get the application ID by run `yarn application -list`. 
Alternatively you can access [YARN's Reource Manager Web UI](https://cloud.google.com/dataproc/docs/concepts/cluster-web-interfaces), click on the hung application, and select "Kill Application".

**Comment by dovy** [comment]
Thanks to your insight I was able to add a fix.

On reconnect of an existing cluster I run:
```
gcloud compute ssh --command 'if [ ! -e "kill_processes.sh" ]; then wget https://storage.googleapis.com/nyt-dataproc/datalab/kill_processes.sh; chmod 777 kill_processes.sh; fi; ./kill_processes.sh' --zone <ZONE> <CLUSTER_NAME>-m
```

`kill_process.sh` is publicly accessible, but the code within is:
```
yarn application -list | grep application_ | grep -v grep | awk '{print $1}' | xargs -I {} yarn application -kill {}
```

This basically kills all yarn applications so the reconnect can connect to the cluster.

Also to clean up the local session manager, I added a keyboard escape handler and run:
```python
        r = requests.get('http://localhost:8081/api/kernels').json()
        print(r)
        for item in r:
            requests.delete("http://localhost:8081/api/kernels/".format(item['id']))
```

This gets me through until the problem is more elegantly resolved.  ;)

**Comment by yebrahim** [comment]
Looks like no more work is needed here. Please reopen if otherwise.
