### ISSUE TITLE
Request - Add pyreadline to Datalab docker container

### ISSUE THREAD

**Issue by dovy** [googledatalab/datalab#1176]
`pip install pyreadline`

This allows for autocomplete within the notebooks.  ;)

**Comment by dovy** [comment]
Though this may not work on the cluster if in gateway mode, but it's a start.

**Comment by dovy** [comment]
It would be great if we could add pip packages in the datalab config as the cluster/machine is being made.

**Comment by chmeyers** [comment]
Adding this would be a change to https://github.com/googledatalab/datalab/blob/master/containers/base/Dockerfile

The main reason we don't add every arbitrary package is the size of the final container, or licensing restrictions.

I'm not going to do it, but since pyreadline is a small package (~100KB) and BSD licensed, I'd accept a pull request for it if you wanted to add it.

**Comment by yebrahim** [comment]
How might this help though? What do we get by just pip installing the package?

I think getting same-cell autocomplete is very helpful, we should look into this if it helps.

**Comment by umang-sh** [comment]
Hi  Guys,
@yebrahim @chmeyers 

this seems like a simple one ,can I take this one?

**Comment by yebrahim** [comment]
Please do!

**Comment by umang-sh** [comment]
Hi Guys ,
@chmeyers @yebrahim 

I have addressed this change in the PR 
https://github.com/googledatalab/datalab/pull/2023

Please review/merge :)

**Comment by ojarjur** [comment]
This has been obsoleted by Jupyter switching over to using the `prompt-toolkit` library, which is included in our latest images.
