### ISSUE TITLE
datalab CLI - Select Zone not Standard

### ISSUE THREAD

**Issue by dovy** [googledatalab/datalab#1182]
FYI, all other gcloud instances provide an index number you can select when selecting zones. You require the full string name. For full consistency, you may want to update that.

**Comment by ojarjur** [comment]
I agree this is an area for improvement.

Other things we should also consider:

1. Validating that the number and/or name of the zone provided is in the list presented to the user (i.e. validate their input).
2. For the create command, if the user specifies a disk-name that already exists in (exactly) one zone, then use that zone (or ask if that is the one they wanted).
3. List the zone that the user most frequently uses first (e.g. "You already have N Datalab instances in us-west1-a")

**Comment by nikhilk** [comment]
Should we tackle this in our CLI or provide information to the user to use gcloud?

**Comment by ojarjur** [comment]
> Should we tackle this in our CLI or provide information to the user to use gcloud?

We do both (document how to use gcloud to set a default, and prompt if none is set), and I think we should continue to do so because we can give the user a better experience that way.

In particular, the experience of having the tool error out and then having to re-run the command (after running `gcloud config set ...`) would annoy me as a user.

**Comment by nikhilk** [comment]
Seems like taking on the burden of staying in sync for consistent
experience esp. if we rely on users initializing their environment with
gcloud init for project/auth.

**Comment by dovy** [comment]
Every component of gcloud seems to do the zone stuff automatically. If that's a concern, maybe you can just grab the code others have. Setting project and such you submit the command so they can do that with gcloud. At least that's what I've seen.

**Comment by ojarjur** [comment]
There are a couple of subtleties that led to the current design, so I'll lay those out so everyone knows the background:

We initially just had the `gcloud` tool prompt for the zone when it needed it, but this causes an issue with the `datalab create` command. That command issues three different gcloud invocations that require a zone (for looking up the disk, creating the disk if it doesn't exist, and then creating the instance), and the zone for all must match.

The approach I went with to address this was to have the datalab CLI prompt for a zone, and then pass that down to gcloud. This has a side benefit that if there is a single matching zone (for commands like `stop`, `connect`, and `delete`), then we can skip the prompt and just use the single zone that we know the VM is in.

There is an alternative approach we could take where we let `gcloud` prompt for the zone of the disk, and then try to get the zone from the gcloud response. However, when the disk does not exist, the `gcloud compute disks describe` method only mentions the selected zone in an error message, and the format of that error message is not guaranteed to be stable. This means that approach would be tricky to implement, and may prove to be brittle in the long run.

That approach would also have the downside that we would have to either give up on the single-zone auto detection, or split that logic out so that it is unrelated to the zone prompting.

**Comment by nikhilk** [comment]
Given this is already implemented, some of this is moot, but I'd personally have chosen to _first_ use "gcloud config list compute/zone" to retrieve zone and if it has not been set, then simply ask the user to complete their gcloud initialization before proceeding (for all datalab commands).

**Comment by chmeyers** [comment]
Omar, can this be closed?

**Comment by ojarjur** [comment]
@chmeyers There is work to do here, but it is not blocking anyone, so it should be classified as a medium-to-low priority feature request.
