### ISSUE TITLE
UX - remove "widgets" menu

### ISSUE THREAD

**Issue by nikhilk** [googledatalab/datalab#1222]
Odd widgets menu item showing in the top-toolbar needs to go away...

**Comment by jimmc** [comment]
The hook to allow ipython to install its ipywidgets menu was added by gramster 10 months ago
(https://github.com/googledatalab/datalab/commit/6bbe1fdef4d288ad6ed539476369b8c696178705#diff-25b786ae3891462b47c12f970983c1c5).
Should we keep it?
If so, PR #1225 fixes visuals rather than removing the menu.

**Comment by nikhilk** [comment]
My opinion is we remove... its unclear how these things work -- download state, etc. We should have more first hand testing before committing to and being able to support the experience they create.
