### ISSUE TITLE
A race condition leads to the /tmp directory not being usable

### ISSUE THREAD

**Issue by bhueth** [googledatalab/datalab#1263]
apt-get update produces the following:

Couldn't create tempfiles for splitting up /var/lib/apt/lists/partial/security.debian.org_dists_jessie_updates_InReleaseCouldn't create tempfiles for splitting up /var/lib/apt/lists/partial/ftp.us.debian.org_debian_dists_testing_InReleaseCouldn't create tempfiles for splitting up /var/lib/apt/lists/partial/deb.debian.org_debian_dists_jessie-updates_InReleaseW: GPG error: http://security.debian.org jessie/updates InRelease: Could not execute 'gpgv' to verify signature (is gpgv installed?)
W: GPG error: http://ftp.us.debian.org testing InRelease: Could not execute 'gpgv' to verify signature (is gpgv installed?)
W: GPG error: http://deb.debian.org jessie-updates InRelease: Could not execute 'gpgv' to verify signature (is gpgv installed?)
E: Couldn't create temporary file to work with /var/lib/apt/lists/deb.debian.org_debian_dists_jessie_Release - mkstemp (2: No such file or directory)

**Comment by chmeyers** [comment]
Omar, due to the "Couldn't create tempfiles for" message, could this be related to the /tmp directory permission issues we've seen?

**Comment by ojarjur** [comment]
@chmeyers Yes, I believe it is the same issue.

We've been able to reproduce this now (although still not consistently).

The issue seems to be some sort of flakiness in the Docker volume mount for `/tmp`. The container believes that `/tmp` is mounted on the correct hard disk (e.g. running `mnt` shows that `/tmp` is mounted from `/dev/sdb`), but any attempt to write to that mount from inside the container fails. Coming from the other side, any writes to the disk from the host work, but they new files do not show up inside the container.

In essence, the container's view of the volume mount, and the host disk's contents seem to be disconnected.

I was never able to find any error messages regarding the mount from any of:

1. The docker logs
2. The kubelet logs
3. The journald logs
4. The output of `dmesg`
5. The serial port output

However, restarting the docker container (e.g. stopping it and letting the kubelet restart it) fixes the issue.

I think we're going to have to address this by just treating the container setup as being unreliable, checking it, and then retrying if anything seems off.

To do that, my plan is to change our entry point to try to write to `/tmp`, and exit if that fails.

We should also do something to check the `/content/datalab` mount (although, interestingly, no one has reported any issues with that one).

**Comment by ojarjur** [comment]
I think I now know why we don't see similar issues with `/content/datalab`.

Our container entrypoint writes several things to that directory (e.g. updating the docs), so any instances where that volume doesn't get mounted will result in the run script exiting and taking the container with it. It would then get restarted by the kubelet until that volume mount is successfully created.

**Comment by ojarjur** [comment]
It looks like my initial understanding of the root cause was wrong.

**Comment by ojarjur** [comment]
I'm now confident that I've found the true root cause of this. It isn't related to Docker, but rather to the startup script that we run inside the VM.

Specifically, [this line](https://github.com/googledatalab/datalab/blob/6e168a7acd5cc6ef59a937ddcde29d1ad2fa2dfd/tools/cli/commands/create.py#L137) tries to clear out all contents of the directory that will be mapped to "/tmp" inside the container.

That runs as part of the startup script, and that (apparently) runs at the same time as the cloud-init config.

This leads to the following race condition:

1. The container is started with a mapping `/mnt/disks/datalab-pd/tmp` to `/tmp`
2. The startup script deletes `/mnt/disks/datalab-pd/tmp`
3. The startup script recreates `/mnt/disks/datalab-pd/tmp`

When this happens, the host directory that is mapped to `/tmp` is gone (but a new directory with the same path exists), so the container can no longer access it.

**Comment by kosukekurimoto** [comment]
%%bash
apt-get update

Get:1 http://ftp.us.debian.org/debian testing InRelease [163 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Ign:1 http://ftp.us.debian.org/debian testing InRelease
Ign:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Ign:3 http://security.ubuntu.com/ubuntu xenial-security InRelease
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Ign:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Get:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Ign:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Fetched 735 kB in 1s (482 kB/s)
Reading package lists...
Couldn't create tempfiles for splitting up /var/lib/apt/lists/partial/ftp.us.debian.org_debian_dists_testing_InReleaseCouldn't create tempfiles for splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial_InReleaseCouldn't create tempfiles for splitting up /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_InReleaseCouldn't create tempfiles for splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-updates_InReleaseCouldn't create tempfiles for splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-backports_InReleaseW: GPG error: http://ftp.us.debian.org/debian testing InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
W: The repository 'http://ftp.us.debian.org/debian testing InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu xenial InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
W: The repository 'http://archive.ubuntu.com/ubuntu xenial InRelease' is not signed.
W: GPG error: http://security.ubuntu.com/ubuntu xenial-security InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
W: The repository 'http://security.ubuntu.com/ubuntu xenial-security InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu xenial-updates InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-updates InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu xenial-backports InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-backports InRelease' is not signed.
