### ISSUE TITLE
Can't Launch Datalab on Server

### ISSUE THREAD

**Issue by dovy** [googledatalab/datalab#1293]
Newest gcloud components and I run `gcloud docker pull gcr.io/cloud-datalab/datalab-gateway` produces: 

```
ERROR: (gcloud.docker) unrecognized arguments:
  pull
  gcr.io/cloud-datalab/datalab-gateway
```

Now my datalab dataproc instances will now no longer launch. Any ideas?

**Comment by ojarjur** [comment]
There was a breaking change to gcloud where you have to add an explicit `--` argument.

I.E. You now have to run `gcloud docker -- pull gcr.io/cloud-datalab/datalab-gateway`

This was just fixed in the Dataproc initialization action [here](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/commit/fec8cf45caca4f4628e63d8c60e75f9851a94d21)

**Comment by dovy** [comment]
When will you be releasing a new image that will fix this?  ;)

**Comment by dovy** [comment]
Ahh, i see. Fixed.
