### ISSUE TITLE
datalab list prints a warning about a deprecated usage

### ISSUE THREAD

**Issue by brandondutra** [googledatalab/datalab#1530]
```
$ datalab list
WARNING: This argument is deprecated. Use `--filter="name =( NAME ... )"` instead.
NAME                     ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP      STATUS
xxxxx
```

with gcloud 164

**Comment by ojarjur** [comment]
This seems to happen for every invocation of `gcloud compute instances list` that provides a `--filter` flag.

It even happens when I run the following command from the Cloud SDK docs (the output of running `gcloud topic filters`):

    gcloud compute instances list --filter='machineType:f1-micro'

I'll reach out to the gcloud team to figure out what is going on here.

**Comment by ojarjur** [comment]
A new version of gcloud was released to fix this issue.
