### ISSUE TITLE
bind: cannot assign requested address

### ISSUE THREAD

**Issue by VicTangg** [googledatalab/datalab#1817]

**Comment by VicTangg** [comment]
Hello, 

Yesterday I was playing around with the Datalab and Dataproc. After running the command on the tutorial page successfully once to connect to my datalab, I cannot connect to datalab any more afterwards.

Now when I run the same 'gcloud compute ssh --zone ....... 8080:host-name-m:8080' command again, it gives me the following responses:

bind: Cannot assign requested address
channel 1: open failed: connect failed: Connection refused.

Could anyone please help me inspect the issue together? There are not many resources online... Thank you very much.

Yours

**Comment by VicTangg** [comment]
Hi,

When I was in

**Comment by VicTangg** [comment]
Hi,

I am a beginner and I am playing with the Datalab. I like the features quite a lot.
After I run the 'gcloud compute ssh --zone ....... 8080:host-name-m:8080' command, Cloud shell outputs 'bind: Cannot assign requested address'. While I can still use the datalab at port 8080, I am not sure whether this message matters or not. Could anyone please help me investigate on this issue together? Thank you!

Yours

**Comment by chmeyers** [comment]
This message is saying that 'gcloud compute ssh' can't use port 8080 because something else is already using it.  

Since it looks like you are running on Cloud Shell, you should use port 8081.  Try switching to 'gcloud compute ssh --zone ....... 8081:host-name-m:8080'

Alternatively, use the 'datalab connect' command.  See https://cloud.google.com/datalab/docs/how-to/datalab-using-shell
