### ISSUE TITLE
can't connect to instance created with custom image from cloud shell

### ISSUE THREAD

**Issue by ryantuck** [googledatalab/datalab#1820]
I've created a simple docker image based on `gcr.io/cloud-datalab/datalab:latest` to use some custom python modules I've written. I've built this locally and have been able to run locally without issue. I've also pushed this up to our project's google container registry. 

From my local machine, I can create and connect to both out-of-the-box datalab instances *and* instances using my custom image:

```
$ datalab create basic-test
$ datalab create --image-name=gcr.io/my-project-name/datalab custom-test
```

From google cloud shell, I am able to create / connect to an out-of-the-box datalab instance:

```
$ datalab create test-from-cloud-shell
```

But when I attempt to create an instance based on a custom image, creation hangs for at least 20 minutes (after which I give up) while waiting for datalab to be reachable:

```
$ datalab create --image-name=gcr.io/xxx/datalab ryan-tuck
Please specify a zone from one of:
...
Your selected zone: 33
Creating the instance ryan-tuck
Created [https://www.googleapis.com/compute/v1/projects/xxx/zones/us-east1-b/instances/ryan-tuck].
Connecting to ryan-tuck.
This will create an SSH tunnel and may prompt you to create an rsa key pair. To manage these keys, see https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys
Waiting for Datalab to be reachable at http://localhost:8081/
```

I've tested this a handful of times with the same result each time. Seems like this is *not* an issue with networking and cloud shell, given that I am able to connect to a basic instance just fine.

**Comment by ryantuck** [comment]
Once this instance is created, I'm able to 

```
gcloud compute ssh datalab@ryan-tuck
```

and it connects instantly.

**Comment by ojarjur** [comment]
The most likely cause for this is the Datalab instance not being able to pull the custom image. We don't have any way to cascade such an error back to the client, so that shows up as the instance never becoming ready.

The most common cause for the VM not being able to pull the image is that the image isn't publicly readable.

We currently only support images that are publicly readable, as the `docker pull` inside of the VM runs without any sort of credentials.

**Comment by ojarjur** [comment]
BTW, both of the issues I described (not reporting errors when pulling the image and not supporting private images) are issues that we should be tracking. I'll add GitHub issues for each one if I can't find a pre-existing ones for them.

**Comment by ojarjur** [comment]
Added https://github.com/googledatalab/datalab/issues/1822 to track supporting non-public GCR images.

**Comment by ryantuck** [comment]
@ojarjur thanks for the quick reply! This generally seems like a reasonable explanation, but I was hoping to clear the following point up:

> We currently only support images that are publicly readable, as the docker pull inside of the VM runs without any sort of credentials.

By this, do you mean that this is only supported *when attempting to create via google cloud shell*, or in general? If so, it doesn't seem that it would apply to my particular problem. 

An additional note for debugging, if it helps, is that I *am* able to readily `datalab connect` to an instance created from a custom image from google cloud shell once it's already been created.

**Comment by ojarjur** [comment]
@ryantuck You are right; I missed the crucial bit where you noted that creating an instance from that custom image worked if you were not on Cloud Shell. Sorry about that.

What you describe is very surprising. I cannot think of any potential cause for such behavior.

First off, I see that Cloud Shell is currently has version 179.0.0 of the Cloud SDK installed. Can you report which version you were using outside of Cloud Shell (so that we can see if something changed that could be causing an issue)? You can find this by running `gcloud version`.

Secondly, there are 4 combinations I can think of to test:

1. Instance created outside of Cloud Shell and connected to outside of Cloud Shell
2. Instance created outside of Cloud Shell and connected to inside of Cloud Shell
3. Instance created inside of Cloud Shell and connected to inside of Cloud Shell
4. Instance created inside of Cloud Shell and connected to outside of Cloud Shell

You said that scenario 1 and 2 are working while scenario 3 is failing; is that correct?

If so, can you also try scenario 4 to see if it works?

**Comment by ryantuck** [comment]
For a 'basic' instance, all 4 scenarios work.

For an instance based on a custom image:

1. Create locally, connect locally **works**
2. Create locally, connect via cloud shell **works**
3. Create via cloud shell, connect locally **does not work**
4. Create via cloud shell, connect via cloud shell **does not work**

My local `gcloud` version is:

```
⚡  ~ ⚡  gcloud version
Google Cloud SDK 168.0.0
alpha 2017.03.24
beta 2017.03.24
bq 2.0.25
core 2017.08.21
datalab 20170525
docker-credential-gcr
gcloud
gsutil 4.27
```

**Comment by ojarjur** [comment]
The version you are using outside of Cloud Shell is from before [we switched the instance template to use systemd instead of the kubelet](https://github.com/googledatalab/datalab/pull/1531).

It's possible that the kubelet is using the VM's service account credentials to authenticate the `docker pull`, in which case it would support private GCR images even if our latest version does not. If that is the case (i.e. if your custom image is not public), then creating the instance from Cloud Shell (or even with a newer version of the Cloud SDK) won't work until we get #1822 fixed.

**Comment by wtgee** [comment]
I'm running into this issue currently. I am unable to connect to custom images from either my local or from cloud shell with the same hang. 

Looking at the `ssh-log-level` output I can see that it authenticates but then gets caught cycling through ports when trying to make tunnel:
```
debug1: Authentication succeeded (publickey).
Authenticated to XXX.XXX.XXX.XXX ([XXX.XXX.XXX.XXX]:22).
debug1: Local connections to localhost:8081 forwarded to remote address localhost:8080
debug1: Local forwarding listening on 127.0.0.1 port 8081.
debug1: channel 0: new [port listener]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: Connection to port 8081 forwarding to localhost port 8080 requested.
debug1: channel 1: new [direct-tcpip]
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
channel 1: open failed: connect failed: Connection refused
debug1: channel 1: free: direct-tcpip: listening port 8081 for localhost port 8080, connect from 127.0.0.1 port 34996 to 127.0.0.1 port 8081, nchannels 2
debug1: Connection to port 8081 forwarding to localhost port 8080 requested.
debug1: channel 1: new [direct-tcpip]
channel 1: open failed: connect failed: Connection refused
debug1: channel 1: free: direct-tcpip: listening port 8081 for localhost port 8080, connect from 127.0.0.1 port 35002 to 127.0.0.1 port 8081, nchannels 2
debug1: Connection to port 8081 forwarding to localhost port 8080 requested.

...keeps going like this
```

Therefore seems like an ssh issue but not sure how to resolve.

Local gcloud used for creation:
```
Google Cloud SDK 184.0.0
alpha 2017.09.15
app-engine-python 1.9.65
beta 2017.09.15
bq 2.0.28
core 2018.01.05
datalab 20171222
docker-credential-gcr 
gcloud 
gsutil 4.28
kubectl 
```

**Comment by wtgee** [comment]
If anyone else gets here, check #1922 and #1928. Still not resolved so it happens automatically but certainly possible to solve.

@ojarjur I recommend closing this issue in favor of #1922

**Comment by ojarjur** [comment]
@wtgee Agreed that this issue should be closed, but since your comment, we have released an updated version of the CLI that *should* handle this automatically now (assuming that the service account has the appropriate permissions).

Regardless, if anyone hits this issue again, please open a new issue to report it.
