### ISSUE TITLE
External PD not attached/identified

### ISSUE THREAD

**Issue by VikramTiwari** [googledatalab/datalab#1898]
At times while connecting to datalab, the external persistent disk is not identified properly. It resolves after a reset of the machine though but is concerning when encountering for the first time. I think that this might be happening when the automatic timeout (1h30m) happens and then I retry to connect to the instance.

**Comment by chmeyers** [comment]
By "identified" you mean that you can't access files on that PD?

This might be an the mount command having an issue.  A little concerning since if it fails we might attempt to format the disk: https://github.com/googledatalab/datalab/blob/master/tools/cli/commands/create.py#L112, but as it works after a reset, we obviously aren't doing a format.

**Comment by VikramTiwari** [comment]
Yes, the datalab page opens up but missing all the files on PD. Seems like it could be an issue with the mount part. Also, just straight up formatting PD doesn't seem like a great idea. Any destructive action should require user consent.

**Comment by ojarjur** [comment]
> Also, just straight up formatting PD doesn't seem like a great idea.

I agree, we can do better here. The format is only meant to happen when attaching an unformatted disk for the first time.

Unfortunately, we don't have a way of checking whether or not this is the first time the disk was attached, but it seems we can explicitly check if it is formatted using the `blkid` command.

I'm going to send out a PR to add that explicit check prior to formatting the disk. I'll also see if I can add some check to verify the disk has been mounted before we proceed with starting the Datalab instance.

**Comment by chmeyers** [comment]
Maybe we should touch a hidden file after mounting it for the first time and check and see if that file exists?

**Comment by ojarjur** [comment]
@chmeyers I think the `blkid` check will be better because it will check exactly what we want to check; whether or not the disk is formatted.

**Comment by ojarjur** [comment]
It looks like the release we included in version 185.0.0 of the Cloud SDK changed this issue from being a rare occurrence to always happening.

Fortunately, we already had the fix for it; but that will not go out until version 186.0.0 of the Cloud SDK, which is expected later this week.

In the mean time, if you are hit by this issue (i.e. you only see an empty "notebooks" directory in your instance and no "docs" directory), you can fix it by restarting your instance.

**Comment by jimmiebtlr** [comment]
Maybe worth it to publicize this a bit more or something?  We definitely saw this and were looking at recovery options for a while before coming across this ticket.

**Comment by chmeyers** [comment]
This is fixed with gcloud 186.0.0 (went out Wednesday)
