### ISSUE TITLE
All of My Notebooks Have Been Deleted

### ISSUE THREAD

**Issue by kenwilly** [googledatalab/datalab#1909]
I was working in datalab this morning with no problem, but when I connected again at about 2:45 PM EST all of my notebooks had been deleted.  Luckily I had backed up my work last night, but when I uploaded a new notebook from my drive I received this error: 

An unknown error occurred while loading this notebook. This version can load notebook formats v4 or earlier. See the server log for details.

Are the two issues related?

**Comment by kenwilly** [comment]
UPDATE: The notebooks were restored when I checked again at 5:30 PM EST, and I am no longer receiving the error.

**Comment by chmeyers** [comment]
Any chance that your VM's disk is nearly full?  I've seen the upload errors like that when Datalab is out of disk space.

**Comment by kenwilly** [comment]
I'm not sure how to verify if the disk is nearly full, but that seems unlikely since I'm just using it to store about 10 notebooks.  No other files are stored on the VM.

**Comment by chmeyers** [comment]
Do you have auto-shutdown enabled, and was the machine reset between the two times you mentioned above?  This sounds like what might happen if the Persistent Disk wasn't properly attached, and then got attached correctly after a reset.  Possibly fixed by https://github.com/googledatalab/datalab/pull/1903 (which hasn't been released yet).

**Comment by kenwilly** [comment]
Auto-shutdown was set to 90 minutes, so that does sound like it could be the issue.  Thanks for the help.
