### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by Philmod** [googledatalab/datalab#1926]
Hey Datalab team,

When I try to reconnect to an existing datalab (using Cloud Shell), it hangs 90% on "Waiting for Datalab to be reacheable...". 

Sometimes I get the same error when I create a new datalab.

The latest problem I got is the datalab couldn't create a notebook because no disk space available, even thought that was a fresh datalab.

Is there any pointer to fix these problems? 
Are these because of my Cloud project?

Thanks,
Philippe

**Comment by Philmod** [comment]
Oh, I also get this error *sometimes* when I want to create a new datalab: "Permission denied (publickey)". From Cloud Shell.

**Comment by chmeyers** [comment]
The "no disk space" issue is due to a problem with https://github.com/googledatalab/datalab/issues/1892, this will be fixed by https://github.com/googledatalab/datalab/issues/1921.  Workaround until then is to do a single Reset of the new VM, so that the disk gets mounted correctly.

I spoke to you offline about the Cloud Shell reconnection issue, which is possibly due to your Company's cloud policies and network/firewall rules.

**Comment by nof20** [comment]
+1 on this.  The same issue also seems to prevent stored notebooks in Cloud Source Repositories being synced with the VM, ad is also fixed by doing a single reset of the VM.

Looking forward to a proper fix for this, it was a frustrating experience in what was otherwise an awesome product.

**Comment by ojarjur** [comment]
Closing this out as #1921 was released long ago.
