### ISSUE TITLE
SQL module parsing needs to ignore comments

### ISSUE THREAD

**Issue by nikhilk** [googledatalab/datalab#600]
Seems like the parsing doesn't account for comments (it finds variables that need replacing even within comments)

Note tried both "-- comments" and /\* */ comments. Don't know if comment handling itself accounts for these.

**Comment by gramster** [comment]
The new tokenizer will handle SQL-style comments correctly. We still drop lines that start with '#'; that is handled as part of the magic in gcp.datalab (while SQL comments are handled as part of Query SQL expansion in gcp.bigquery). The rationale for the former is that we can have leading Python code, but it happens in the SQL code too. I'll fix that in a separate branch so '#' does not affect the SQL queries. Correcting the variable expansion in SQL comments will have to wait until the new UDF code is in so we can leverage the tokenizer instead of the current regexps.

**Comment by qimingj** [comment]
LGTM. Thanks for the explanation.
