### ISSUE TITLE
datalab does not resolve a conflict preventing me from commit

### ISSUE THREAD

**Issue by akhlopotin** [googledatalab/datalab#774]
I discarded the last (bad) commit at git cmd line via reset --hard HEAD~1, but GUI datalab keeps looking at that last commit that was discarded. There was a conflict to and I got through resolving the conflict and taking the local copy but then the commit button is disabled although there are other modified files waiting for a commit. Upon reloading GUI datalab it again shows the unresolved conflict

**Comment by parthea** [comment]
I had issues with the datalab git GUI as well (see #667 ).

To **temporarily** work around the issue I've installed datalab locally on my laptop. That way I can run notebook locally to test it out, then commit them from the same local setup using command line git or another git client tool. It is working well for me.  

To install datalab locally, follow the steps here:
https://github.com/googlecloudplatform/datalab/wiki/Development-Environment

Make sure to apply the patch from the following pull request on the source code
https://github.com/GoogleCloudPlatform/datalab/pull/588

Other useful commands to run:

- On the host machine , run `gcloud init` from the folder `$REPO_DIR/containers/datalab/content` and clone your google repository into the `'default'` folder. Note, you may have to checkout another branch. For example, either `'datalab'` or `'datalab_<DATALAB_INSTANCE_NAME>'`

- In order to see your git repo content in datalab, follow this step. On the host machine, edit `$REPO_DIR/containers/datalab/run.sh` and change
`-v $REPO_DIR/content:/content \`
to
`-v $REPO_DIR/containers/datalab/content/default:/content \`

- After running datalab, In a datalab notebook run `gcloud config set project <your cloud project>`


This is only a temporary work around to use while the gui is being improved (although I'm really getting used to the local setup!) . 

If you want to try to run datalab locally and get stuck, feel free to post your question here and I'll try to help.

**Comment by yebrahim** [comment]
Closing as obsolete, since we moved away from Google Source Repositories as the main git UI.
