### ISSUE TITLE
Add ipywidgets extension

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [googledatalab/datalab#843]
Today the ipywidgets extension is disabled:
```
# Include this line above to enable ipywidgets. These aren't working 100% yet so 
# we don't enable them.
#    jupyter nbextension enable --py widgetsnbextension && \
```
It will be nice to propose working solution.

**Comment by gramster** [comment]
AFAICT this is probably due to some CSS conflicts. In master now we can
enable the widgets but if we create (say) a slider the slider does not move
as we drag even though the value changes. Getting them to work is not a
high priority for us right now; its more a nice to have, and perhaps
someone with more knowledge of the innards of ipywidgets can take this on
and submit a PR. If we get to the point where it makes sense for us to
build some of our functionality in the form of a widget that would raise
the priority, but that isn't the case yet.
