### ISSUE TITLE
Local container: Cleanup additions to top level directory ~/datalab

### ISSUE THREAD

**Issue by Di-Ku** [googledatalab/datalab#849]
I see the following after running the local container and one of the tutorials:
All but docs/ and notebooks/ should be out of sight (hidden directory perhaps) - associated mystery - why is gcloud being run from inside?

configurations
docs
logs
notebooks
active_config
application_default_credentials.json
credentials
gce

**Comment by gramster** [comment]
active_config
application_default_credentials.json
credentials
gce
configurations

should no all go under a hidden .config directory now.

I'm not sure about logs; what is that?

gcloud is being run by the node server in order to set the user account; without that using gcloud will fail when using user credentials.

**Comment by ojarjur** [comment]
This was changed long ago. Now, the only directories that will be visible are "docs" and "notebooks".
