### ISSUE TITLE
Blank Screen in Python Notebook http://localhost:8081

### ISSUE THREAD

**Issue by mosicr** [googledatalab/datalab#950]
I am on Ubuntu 16.04
I am getting blank screen when I hit http://localhost:8081 ( I got passed "Accept" button ). 
Command I ran to get setup running is ( I changed project_id, zone, instance name ):
sudo docker run -it -p "127.0.0.1:8081:8080" -v "${HOME}:/content" -e "GATEWAY_VM=project_id/us-east1-b/vm-instance-name" gcr.io/cloud-datalab/datalab:local

iptables are off

**Comment by parthea** [comment]
My initial thought is to try the following:

1. Run `docker pull gcr.io/cloud-datalab/datalab:local` which checks to see whether you have the latest datalab image, and downloads a new image if required.
2. Run the command below without `sudo`. I also temporarily removed the `127.0.0.1` local only binding from the command just to rule whether it is related to your issue (it needs to be there for security purposes but its helpful to know whether the issue is resolved when `127.0.0.1:` is removed)
Use `docker run -it -p "8081:8080" -v "${HOME}:/content" -e "GATEWAY_VM=project_id/us-east1-b/vm-instance-name" gcr.io/cloud-datalab/datalab:local`

Also, it would be helpful to see the full console output. Can you include that here?

@ojarjur Have you seen this symptom before (blank page)?

**Comment by mosicr** [comment]
I am runnig it all as sudo su: 
1) sudo su
[sudo] password for myname: 
root@myname-Vostro-1015:/home/myname# docker pull gcr.io/cloud-datalab/datalab:local
local: Pulling from cloud-datalab/datalab

357ea8c3d80b: Already exists 
a3ed95caeb02: Already exists 
8181620f86fe: Already exists 
c16fd881d805: Already exists 
5f20e536d89d: Already exists 
5a94c356c7f0: Already exists 
8ea4363051b8: Already exists 
94ab3fb01cb9: Already exists 
8e972ce0ece2: Already exists 
2a1717a83b09: Already exists 
9ad679799370: Already exists 
fd1cf3a2fb9e: Already exists 
1ec8ce7f6a94: Already exists 
d89c41074aeb: Already exists 
6ae1316f8be1: Already exists 
675e7d897beb: Already exists 
9e81158ff7bb: Already exists 
02ccb94bbd7c: Already exists 
9d2cdf051f00: Already exists 
8b49091f245f: Already exists 
Digest: sha256:7d7c1675e06c8b53b8b58f316122e3ffbd08fa66e2631342eeb6a1ba9a071d18
Status: Image is up to date for gcr.io/cloud-datalab/datalab:local

**Comment by parthea** [comment]
Great!  At your earliest convenience, please also include the full output from the following:
`docker run -it -p "8081:8080" -v "${HOME}:/content" -e "GATEWAY_VM=project_id/us-east1-b/vm-instance-name" gcr.io/cloud-datalab/datalab:local`

**Comment by mosicr** [comment]
Here it is ( I am still having same problem ):
[a.txt](https://github.com/googledatalab/datalab/files/428351/a.txt)

**Comment by mosicr** [comment]
- I hit http://localhost:8081/ 
- "Accept" button shows up ( if there is no ~/datalab directory ); I click on it
- path expands to http://localhost:8081/tree/datalab
- blank screen shows up

**Comment by parthea** [comment]
@mosicr I have the file. You can remove it from here since there is project specific information inside.

**Comment by mosicr** [comment]
Done thanks :-)

**Comment by parthea** [comment]
I was able to reproduce the error `'timeout'` in the console as well as the symptom(blank page) , but I had to modify the source code. I reduced the timeout that is used to determine whether there was a failure starting the Jupyter server.

In line 175 in [jupyter.ts](https://github.com/googledatalab/datalab/blob/master/sources/web/datalab/jupyter.ts)
I changed the line from from `tcp.waitUntilUsed(server.port, 100, 3000).then(` to `  tcp.waitUntilUsed(server.port, 100, 800).then(`

I see the following in the console.
```
{"name":"app","hostname":"2022742d160f","pid":165,"type":"jupyter","level":30,"msg":"[9000]: Loaded config file: /root/.jupyter/jupyter_notebook_config.py\n","time":"2016-08-20T16:08:43.635Z","v":0}
{"name":"app","hostname":"2022742d160f","pid":165,"type":"jupyter","level":30,"msg":"[9000]: Looking for jupyter_notebook_config in /\n","time":"2016-08-20T16:08:43.636Z","v":0}
{"name":"app","hostname":"2022742d160f","pid":165,"type":"jupyter","level":30,"msg":"[9000]: Config changed:\n{'FileContentsManager': {'root_dir': u'/content'}, 'TemplateExporter': {'template_path': <traitlets.config.loader.LazyConfigValue object at 0x7fc37d47b910>}, 'KernelManager': {'autorestart': True}, 'HTMLExporter': {'template_file': 'html'}, 'NotebookNotary': {'algorithm': 'sha1'}, 'Session': {'keyfile': '', 'key': ''}, 'MappingKernelManager': {'root_dir': u'/content'}, 'NotebookApp': {'allow_origin': '*', 'enable_mathjax': False, 'log_level': 10, 'ip': '127.0.0.1', 'answer_yes': True, 'port_retries': 0, 'notebook_dir': '/content', 'open_browser': False, 'log_format': '%(message)s', 'port': 9000}, 'ContentsManager': {'untitled_notebook': 'Untitled Notebook', 'untitled_directory': 'Untitled Folder', 'untitled_file': 'Untitled File'}, 'KernelSpecManager': {'whitelist': ['python2']}}\n","time":"2016-08-20T16:08:43.644Z","v":0}
{"name":"app","hostname":"2022742d160f","pid":165,"type":"jupyter","level":30,"msg":"[9000]: Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret\n","time":"2016-08-20T16:08:43.657Z","v":0}
{"name":"app","hostname":"2022742d160f","pid":165,"level":50,"err":{"message":"timeout","name":"Error","stack":"Error: timeout\n    at timeoutFunc (/datalab/web/node_modules/tcp-port-used/index.js:192:25)\n    at Timer.listOnTimeout (timers.js:92:15)"},"msg":"Failed to start Jupyter server for user anonymous.","time":"2016-08-20T16:08:43.771Z","v":0}
```

I played around with the timeout value, and it seemed that 800 ms triggered the error while 900 ms did not.

Can you share the specs of your linux machine, in order to determine whether increasing the timeout in line 175 would solve your issue?

Also, it would be useful to know what ports are in use inside the datalab container.  To find out the ports in use, follow the steps below.

1.In terminal , run the following command to enter bash inside the container ` docker exec -t -i $( docker ps -q -f ancestor=datalab) /bin/bash`
2. Inside the container, run `apt-get install nmap` to install nmap which will provide the information we need.
3. Inside the container, run ` nmap -sT -O localhost` to view ports in use.

For example, Here is the output from `nmap` when I simulated the error. I can see that port 9000 was actually in use.

```
root@xxxxxx:/# nmap -sT -O localhost

Starting Nmap 6.47 ( http://nmap.org ) at 2016-08-20 16:22 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00030s latency).
Other addresses for localhost (not scanned): 127.0.0.1
Not shown: 997 closed ports
PORT     STATE SERVICE
8080/tcp open  http-proxy
8082/tcp open  blackice-alerts
9000/tcp open  cslistener
Device type: general purpose
Running: Linux 3.X
OS CPE: cpe:/o:linux:linux_kernel:3
OS details: Linux 3.7 - 3.15
Network Distance: 0 hops

OS detection performed. Please report any incorrect results at http://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 2.59 seconds

```

**Comment by parthea** [comment]
If you're running linux in a virtual environment, can you try increasing the specs of the linux VM, just to see if the issue goes away? That will help confirm that the timeout value that is used to wait for Jupyter server to start needs to be increased.

**Comment by mosicr** [comment]
Where is jupyter.ts file - I couldn't find it on my machine. It is bare metal Ubuntu install ( no VM ), on an old laptop ( Intel Core Duo, 2GB RAM ).

**Comment by mosicr** [comment]
2. nmap output ( before and after I hit localhost:8081 )

root@bfe7824c958b:/# nmap -sT -O localhost

Starting Nmap 6.47 ( http://nmap.org ) at 2016-08-21 05:30 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.0024s latency).
Other addresses for localhost (not scanned): 127.0.0.1
Not shown: 998 closed ports
PORT     STATE SERVICE
8080/tcp open  http-proxy
8082/tcp open  blackice-alerts
Device type: general purpose
Running: Linux 3.X
OS CPE: cpe:/o:linux:linux_kernel:3
OS details: Linux 3.7 - 3.15
Network Distance: 0 hops

OS detection performed. Please report any incorrect results at http://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 5.53 seconds
root@bfe7824c958b:/# nmap -sT -O localhost

Starting Nmap 6.47 ( http://nmap.org ) at 2016-08-21 05:31 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.0021s latency).
Other addresses for localhost (not scanned): 127.0.0.1
Not shown: 996 closed ports
PORT     STATE SERVICE
8080/tcp open  http-proxy
8082/tcp open  blackice-alerts
9000/tcp open  cslistener
9001/tcp open  tor-orport
Device type: general purpose
Running: Linux 3.X
OS CPE: cpe:/o:linux:linux_kernel:3
OS details: Linux 3.7 - 3.15
Network Distance: 0 hops

OS detection performed. Please report any incorrect results at http://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 5.52 seconds

**Comment by mosicr** [comment]
I am guessing jupyter.ts is part of docker image. Is there a way to override it i.e. to change timeout setting for a particular run ?

**Comment by parthea** [comment]
I've created a few steps here that should get you up and running with custom datalab image that uses a timeout of 15 seconds (15000 below). This is a short term solution until a fix is added to `gcr.io/cloud-datalab/datalab:local`. I've started the process with pull request #951 .

1. Create a folder called custom_datalab by running `mkdir custom_datalab`
2. `cd` to the custom_datalab folder and create a file in the otherwise empty folder called `Dockerfile` . Paste the Dockerfile code I've included below and save the file.
3. `cd` to the custom_datalab folder and run `sudo docker build -t customized_datalab .`  
You need the `.` at the end of the command, so make sure not to exclude it
4. Run the following command `docker run -it -p "127.0.0.1:8081:8080" -v "${HOME}:/content" -e "GATEWAY_VM=project-id/zone/vm-instance-name" customized_datalab`


Dockerfile code:
```
FROM gcr.io/cloud-datalab/datalab:local
RUN sed -i -e 's/tcp.waitUntilUsed(server.port,\ 100,\ 3000)/tcp.waitUntilUsed(server.port,\ 100,\ 15000)/g' /datalab/web/jupyter.js 
```

Please let me know if this works!

**Comment by mosicr** [comment]
Works !!
You da man.
Thank you very much, greatly appreciated !!

**Comment by parthea** [comment]
I'm glad the solution worked!

**Comment by mosicr** [comment]
Works !!
You da man.
Thank you very much, greatly appreciated !!

**Comment by ojarjur** [comment]
@parthea Thanks, so much for debugging this!

**Comment by NamTuanNguyen** [comment]
Works like a charm! Thanks. 
On the other side, I understand datalab is still beta version, but it surely didnt meet my expectation.

**Comment by parthea** [comment]
@NamTuanNguyen I'm happy that this helped. I believe this work around is no longer required with the latest Datalab image. 

Use `docker pull FROM gcr.io/cloud-datalab/datalab:local` to get the latest version. 

Please could you try pulling the latest version and confirm that this work around is no longer required?

**Comment by matrixor** [comment]
I use Windows 10 and Docker Toolbox 

C:\Users\Matrixor>docker run -it -p "127.0.0.1:8081:8080" -v "/C/Users/Matrixor/Documents/:/content" -e "PROJECT_ID=xxxx-xxxx-xxxxx" -e "DATALAB_DEBUG=true" gcr.io/cloud-datalab/datalab:local
/ /
From https://github.com/googledatalab/notebooks
 * branch            master     -> FETCH_HEAD
HEAD is now at 585ecb3 Update contributing doc to include requirement of JSON key in single quotes (#29) (#29)
/
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Open your browser to http://localhost:8081/ to connect to Datalab.
{"name":"app","hostname":"e4cc19625be7","pid":58,"level":30,"msg":"Starting DataLab server at http://localhost:8080","time":"2016-12-24T16:28:47.688Z","v":0}

I tried ssh to Docker server  and could see /C/Users/Matrixor/Documents/datalab was created. 

however, when I tried http://localhost:8081, there site can't be reached.
