### ISSUE TITLE
Datalab server started but not being able to access it in browser

### ISSUE THREAD

**Issue by aashrairavooru** [googledatalab/datalab#960]
I am able to successfully start the datalab server using the docker run command as per the [datalab quickstart](https://cloud.google.com/datalab/docs/quickstarts/quickstart-gce) but not being able to access it in my browset at localhost:8081.

**Comment by parthea** [comment]
Hello Aashrai,

Please could you share what operating system you are using, and the output from the console?

Include the full output after the following lines from the console:
```
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
```

**Comment by aashrairavooru** [comment]
Sorry for the late response, we are getting something like this.
{"name":"app","hostname":"d9a2724dea6c","pid":181,"level":30,"msg":"Starting DataLab server at http://localhost:8080","time":"2016-09-06T08:02:24.936Z","v":0}

OS: OSX 10.11.6

PS:We ran this on a OSX 10.11.5 machine and it is working fine with the same setup.

**Comment by aashrairavooru** [comment]
Hey guys any updates on this?

**Comment by ojarjur** [comment]
@aashrairavooru Can you give more details about what you are seeing? (e.g. does the browser hang, does it report an error message, etc).

Also, can you try to run the nginx container on port 8081 and see if it is accessible? That will tell us if there is some sort of firewall issue:

    docker run -d -p 8081:80 --name webserver nginx

**Comment by VelizarVESSELINOV** [comment]
@aashrairavooru I got similar issue when I was running Docker with VirtualBoxVM old version on Mac, when I switched to the new version it is working better.

**Comment by aashrairavooru** [comment]
@ojarjur we get an error saying the localhost was unable to connect I doubt it's a firewall issue we went through the firewall steps mentioned in the quickstart and it was working sometime back and suddenly stopped working since a few weeks.

**Comment by ojarjur** [comment]
@aashrairavooru The firewall steps in the quickstart are for the Google Compute Engine firewall, whereas what I am wondering about is a firewall on your local machine.

Can you try the nginx command and confirm whether or not you are able to connect to it?  I don't know of a potential issue that you might be hitting, so we have to narrow down to the root cause one step at a time.

Also, is "localhost was unable to connect" the exact error message that you got from the browser? If not, can you let me know what the exact error message was?

**Comment by anandanimesh** [comment]
@ojarjur The firewall in the local machine is off, and even then we are getting the error message when trying to connect to the datalab server.

The exact error message that we get is **This site can’t be reached. localhost refused to connect.
**

**Comment by ojarjur** [comment]
@anandanimesh Are you running "Docker for Mac" or "Docker Toolbox"?

We had seen that sort of issue before with Docker Toolbox (which is one of the reasons we can't support it), but haven't encountered that with Docker for Mac.

One thing to check is if the Docker container is successfully connecting to "localhost" on your machine.

Try:

    docker run -d -p 8081:80 --name webserver nginx

And:

    docker run -d -p localhost:8081:80 --name webserver nginx

And see if you are able to connect to the nginx hello world server in each case. If you can connect to the first one, but not the second, then that means the issue is in limiting the port binding to localhost.

**Comment by aashrairavooru** [comment]
Yeah that was the problem we had both docker and docker toolbox installed we removed docker toolbox and works fine now. I think sometime we might have started docker toolbox by mistake once

**Comment by ojarjur** [comment]
@aashrairavooru Thanks for keeping us updated; I'm glad to hear that it is working for you now.

**Comment by HintikkaKimmo** [comment]
@ojarjur could you clarify the issues with docker toolbox? I kinda needed it for other stuff can I just install docker for mac together with docker toolbox and use datalab
